// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7QZnwMQQbhD44ZNQ3BUh7vOWYElyZ1Ak',
    appId: '1:995145015331:web:c28653c784ba792a96d196',
    messagingSenderId: '995145015331',
    projectId: 'khoj-5415b',
    authDomain: 'khoj-5415b.firebaseapp.com',
    databaseURL: 'https://khoj-5415b-default-rtdb.firebaseio.com',
    storageBucket: 'khoj-5415b.appspot.com',
    measurementId: 'G-2K6C7BSC42',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFco6IlujZlKEbn0E3q6Jb8LJaDBaVVMM',
    appId: '1:995145015331:android:3bf27b8f7e1ada7996d196',
    messagingSenderId: '995145015331',
    projectId: 'khoj-5415b',
    databaseURL: 'https://khoj-5415b-default-rtdb.firebaseio.com',
    storageBucket: 'khoj-5415b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPMOYRnNUYcQeLDEX6FttxIF6DW2Z6roM',
    appId: '1:995145015331:ios:173e29afebe57df596d196',
    messagingSenderId: '995145015331',
    projectId: 'khoj-5415b',
    databaseURL: 'https://khoj-5415b-default-rtdb.firebaseio.com',
    storageBucket: 'khoj-5415b.appspot.com',
    androidClientId: '995145015331-tluigvlehodp98uokpb37chm6pm0nb5v.apps.googleusercontent.com',
    iosClientId: '995145015331-kni5uf54o0avjbubj097ps5t4e0v9m2m.apps.googleusercontent.com',
    iosBundleId: 'com.spd.khoj',
  );
}
